=== BharanitharanR/task-challenge-backend/project-banyan-compiler/src/main/resources/schemas/ruleset.schema.json
{
  "$schema": "https://json-schema.org/draft/2020-12/schema",
  "$id": "https://banyan.dev/schemas/ruleset.schema.json",
  "title": "RulesetDefinition",
  "type": "object",
  "required": ["kind", "id", "version", "spec"],
  "additionalProperties": false,

  "properties": {
    "kind": {
      "type": "string",
      "const": "Ruleset"
    },
    "id": {
      "type": "string",
      "pattern": "^[a-z][a-z0-9_\\-]{2,100}$"
    },
    "version": {
      "type": "integer",
      "minimum": 1
    },
    "spec": {
      "type": "object",
      "required": ["expression"],
      "additionalProperties": false,
      "properties": {
        "expression": {
          "$ref": "#/$defs/expression"
        }
      }
    }
  },

  "$defs": {
    "expression": {
      "oneOf": [
        { "$ref": "#/$defs/ruleRefNode" },
        { "$ref": "#/$defs/logicalNode" }
      ]
    },

    "ruleRefNode": {
      "type": "object",
      "required": ["ruleRef","version"],
      "additionalProperties": false,
      "properties": {
        "ruleRef": {
          "type": "string",
          "minLength": 1
        },
        "version": {
          "type": "integer",
          "description": "version of rule"
        }
      }
    },

    "logicalNode": {
      "type": "object",
      "required": ["operator", "operands"],
      "additionalProperties": false,
      "properties": {
        "operator": {
          "type": "string",
          "enum": ["AND", "OR"]
        },
        "operands": {
          "type": "array",
          "minItems": 2,
          "items": {
            "$ref": "#/$defs/expression"
          }
        }
      }
    }
  }
}

=== BharanitharanR/task-challenge-backend/project-banyan-compiler/src/test/resources/driving_lesson/driving_india_ruleset.json
{
  "kind": "Ruleset",
  "id": "driving_india_ruleset",
  "version": 1,
  "spec": {
    "expression": {
      "operator": "AND",
      "operands": [
        {
          "operator": "OR",
          "operands": [
            {
              "ruleRef": "driving_lane_departure_count_rule",
              "version": 1
            },
            {
              "ruleRef": "driving_over_speed_limit_rule",
              "version": 1
            }
          ]
        },
        {
          "ruleRef": "driving_india_rule", "version": 1
        }
      ]
    }
  }
}

=== BharanitharanR/task-challenge-backend/project-banyan-compiler/src/test/resources/sample_challenge_source_zip/unzipped_file_sources/basic_ruleset.json
{
  "kind": "Ruleset",
  "id": "basic_ruleset",
  "version": 1,
  "spec": {
    "expression": {
      "operator": "OR",
      "operands": [
        {
          "operator": "AND",
          "operands": [
            {
              "operator": "OR",
              "operands": [
                { "ruleRef": "max_failed_attempts","version": 1 },
                { "ruleRef": "max_incorrect_passwords_history_greater_than_three", "version": 1 }
              ]
            },

            { "ruleRef": "within_business_hours", "version": 2 }
          ]
        },
        {
          "ruleRef": "ip_not_blacklisted", "version": 1
        }
      ]
    }
  }
}

=== BharanitharanR/task-challenge-backend/project-banyan-compiler/src/test/resources/ruleset/semantic/valid/nested_Multi_Laye_ruleset.json
{
  "kind": "Ruleset",
  "id": "nested_multi_layer_ruleset",
  "version": 1,
  "spec": {
    "expression": {
      "operator": "OR",
      "operands": [
        {
          "operator": "AND",
          "operands": [
            {
              "operator": "OR",
              "operands": [
                { "ruleRef": "max_failed_attempts" },
                { "ruleRef": "max_incorrect_passwords_history_greater_than_three" }
              ]
            },

            { "ruleRef": "within_business_hours" }
          ]
        },
        {
          "ruleRef": "ip_not_blacklisted"
        }
      ]
    }
  }
}

=== BharanitharanR/task-challenge-backend/project-banyan-compiler/src/test/resources/ruleset/schema/valid/nested_ruleset.json
{
  "kind": "Ruleset",
  "id": "nested_ruleset",
  "version": 1,
  "spec": {
    "expression": {
      "operator": "OR",
      "operands": [
        {
          "operator": "AND",
          "operands": [
            { "ruleRef": "max_failed_attempts", "version": 1 },
            { "ruleRef": "within_business_hours", "version": 1 }
          ]
        },
        {
          "ruleRef": "ip_not_blacklisted", "version": 1
        }
      ]
    }
  }
}
